<?php

/**
 * @file
 * Runtime hooks.
 */

/**
 * Quick access to the ExposeStatus service / singleton.
 *
 * Use 'drush ev "expose_status_instructions()"'.
 */
function expose_status_instructions() {
  print(PHP_EOL);
  print(\Drupal::service('expose_status')->instructions() . PHP_EOL);
  print(PHP_EOL);
  print('See module README.md file for more details.' . PHP_EOL);
  print(PHP_EOL);
}

/**
 * Quick access to print the token.
 *
 * Use 'drush ev "expose_status_token()"'.
 */
function expose_status_token() {
  print(\Drupal::service('expose_status')->token());
}
